<a href="https://colab.research.google.com/github/haaaram/MS-AIschool/blob/main/01.Python/09_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy

# C언어로 개발된 파이썬에서 과학적 계산을 위한 핵심 라이브러리. 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다. 하지만 고수준의 데이터 분석 기능을 제공하지는 않기 때문에 Numpy 배열과 함께 Pandas와 같은 도구를 함께 사용힌다.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# zeros, ones, empty를 사용해서 배열을 생성한다.
car = np.zeros((3,3))
print(car)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.empty((4,4))

array([[3.03598913e-316, 0.00000000e+000, 6.91740643e-310,
        6.91734389e-310],
       [1.32882766e+179, 4.79243676e-322, 2.53351330e-316,
        6.91740685e-310],
       [2.30908182e+251, 1.27701001e+232, 4.24669921e+175,
        1.05092727e-153],
       [1.12963434e+277, 1.70647318e+155, 5.38206259e+228,
        1.27734658e-152]])

In [ ]:
# 특정 범위의 변수를 생성할 때 arange()를 사용한다.

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인해보기
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 차원 확인
arr.ndim

2

In [ ]:
# 데이터의 모양을 확인하는 방법
arr.shape

(2, 3)

In [ ]:
# 데이터 타입의 확인
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
# ndarray 배열의 타입 변환 n-th dimension
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)
print(arr_float.dtype)

int64
float64


In [ ]:
arr_str = np.array(['1', '2', '3', '4'])
print(arr_str.dtype)
arr_int = arr_str.astype(np.int64)
print(arr_int.dtype)

<U1
int64


In [ ]:
# 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [ ]:
print(np.add(arr1, arr2))
print(np.multiply(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [ ]:
#ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
arr_1 = arr[:2, 1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr[0,2]

3

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [ ]:
arr[idx]

array([4, 5, 6])

In [ ]:
redwine = np.loadtxt(fname='winequality-red.csv', delimiter=';', skiprows=1)

In [ ]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
# 기초 통계 함수
# sum   합계
# mean  평균
# std   표준편차
# var   분산(std의 제곱)
# min   최소값
# max   최대값

print(redwine.sum())
print(redwine.sum(axis=0))
print(redwine.mean(axis=0))

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [ ]:
# print(redwind[:]) //전체 데이터 출력
#redwine.mean(axis=1)
print(redwine[:,0].mean()) #첫 번째 칼럼의 값으로만 평균을 냄

8.31963727329581


In [ ]:
print(redwine.max(axis=0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
